version: 2.1

jobs:
  test-mysql:
    parameters:
      php-version:
        type: string
    docker:
      - image: aimeos/ci-php:<< parameters.php-version >>
      - image: mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: aimeos
          MYSQL_USER: aimeos
          MYSQL_PASSWORD: aimeos
    steps:
      - checkout
      - run: git clone --depth=50 --branch=master https://github.com/aimeos/aimeos-core ../aimeos-core
      - run: cd .. && mv project aimeos-core/ext/ai-admin-mcp && mv aimeos-core project && cd project
      - restore_cache:
          keys:
            - php<< parameters.php-version >>-{{ checksum "composer.json" }}
      - run: composer req --no-update "aimeos/prisma:dev-master" "nyholm/psr7:~1.2"
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php<< parameters.php-version >>-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: echo "<?php return array( 'db' => array( 'adapter' => 'mysql', 'host' => '127.0.0.1', 'port' => 3306, 'database' => 'aimeos', 'username' => 'aimeos', 'password' => 'aimeos', 'limit' => 2, 'opt-persistent' => false, 'stmt' => array( \"SET SESSION sort_buffer_size=2097144; SET NAMES 'utf8'; SET SESSION sql_mode='ANSI'\" ) ), 'fs' => array( 'adapter' => 'Standard', 'basedir' => '.' ), 'mq' => array( 'adapter' => 'Standard', 'db' => 'db' ) );" > config/resource.php
      - run: for i in `seq 1 10`; do nc -z 127.0.0.1 3306 && echo OK && exit 0; echo -n .; sleep 1; done
      - run: ./vendor/bin/phing -Ddir=ext/ai-admin-mcp setup testext

workflows:
  unittest:
    jobs:
      - test-mysql:
          matrix:
            parameters:
              php-version: ["8.2", "8.3", "8.4", "8.5"]
